### ISSUE TITLE
Image plots (e.g. EDISP, PSF) incorrect with Matplotlib > 2

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#823]
In #816 and https://github.com/gammapy/gammapy-extra/pull/44 , @jjlk added files and a class to access CTA prod 2 IRFs.

As mentioned in https://github.com/gammapy/gammapy/pull/816#issuecomment-266420658, there's a potential issue with EDISP.

@joleroi - Can you try this, as a first step?
```python
from gammapy.irf import EnergyDispersion
EnergyDispersion.read('$GAMMAPY_EXTRA/datasets/cta/perf_prod2/CTA-Performance-South-20150511/CTA-Performance-South-50h_20150511.fits')
edisp = EnergyDispersion.read('$GAMMAPY_EXTRA/datasets/cta/perf_prod2/CTA-Performance-South-20150511/CTA-Performance-South-50h_20150511.fits')
print(edisp)
edisp.plot_matrix()
```
The plotted EDISP is correct for @jjlk , but not for me.

Here's my version info, in case it helps to reproduce or narrow down the issue:
* Python 3.5
* Numpy 1.11.2
* Scipy 0.18.1
* Matplotlib: 2.0.0b4.post2992+g02bde2182
* Astropy: 2.0.dev17497
* Gammapy: 0.6.dev3906

**Comment by cdeil** [comment]
It's just a Matplotlib plotting issue. If I go back to the latest stable MPL 1.5.3, the plot is OK for me.

Assigning this issue to myself, to see if we should improve our plotting code or if I should file a bug report in the MPL tracker.

**Comment by cdeil** [comment]
I've tracked this down to a change in MPL behaviour in the upcoming MPL 2.0 release:
http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#interpolation

If I pass `resample=False` to the `imshow` call in `plot_matrix`, I get the same result as with MPL 1.x.

This needs to be fixed for every `imshow` call in Gammapy in a way that gives the same output with MPL 1.x and 2.x. I'll think about it a bit and implement a solution in January.

**Comment by TarekHC** [comment]
Not sure if it will help much, but together with @mackaiver , we found an issue that is probably related to this one. 

If you execute the following code (taken from the image_analysis notebook):
```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.convolution import Ring2DKernel, Tophat2DKernel

from gammapy.data import DataStore
from gammapy.image import SkyImage, SkyImageList
from gammapy.detect import KernelBackgroundEstimator as KBE


data_store = DataStore.from_dir('$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2/')
source_pos = SkyCoord(83.633083, 22.0145, unit='deg')
ref_image = SkyImage.empty(
    nxpix=400, nypix=400, binsz=0.02,
    xref=source_pos.ra.deg, yref=source_pos.dec.deg,
    coordsys='CEL', proj='TAN',
)
# Make a counts image for a single observation
events = data_store.obs(obs_id=23523).events
counts_image = SkyImage.empty_like(ref_image)
counts_image.fill_events(events)

# If you have internet access, you could also use this to define the `source_pos`:
from astropy.coordinates import SkyCoord
source_pos = SkyCoord.from_name('crab')
norm = counts_image.plot_norm(stretch='sqrt', min_cut=0, max_cut=0.3)
fig, axes, cbar = counts_image.smooth(radius=0.1 * u.deg).plot(norm=norm, add_cbar=True)
```

It plots a beautiful counts map. But if you add a cross in the position of the Crab Nebula:

```python
axes.plot(source_pos.ra.deg, source_pos.dec.deg, marker='+', color='white', mew=1, ms=30,  transform=axes.get_transform('fk5'))
```

The plot is distorted, but ONLY if you are using an old Matplotlib version (I'm on Matplotlib: 1.5.1, @mackaiver in 2.0.0).

**Comment by cdeil** [comment]
My guess is that the sky image plotting issue is unrelated to this issue.
@adonath - Could you try the example they give with MPL 1.5, please?

Here's what I get with MPL 2.0, i.e. what the expected version looks like:
<img width="752" alt="screen shot 2017-02-23 at 23 53 05" src="https://cloud.githubusercontent.com/assets/852409/23282826/555e67ac-fa23-11e6-979a-ade5245ed7d3.png">

**Comment by cdeil** [comment]
@kosack suggested we call `pcolormesh` instead of `imshow` to fix this issue with many of our plots. I've never used `pcolormesh` before, so I don't know yet if we should go that way or just fix our call arguments passed to `imshow`.

Here's some info: http://stackoverflow.com/questions/21166679/when-to-use-imshow-over-pcolormesh

It sounds like `pcolormesh` is a bit more flexible and maybe we should use it?

One question I have: if saved as PDF, will `pcolormesh` save the pixels as a bitmap?
This is what `imshow` does, and ROOT draws a circle with boundary rectangle for every pixel, resulting in PDFs that are horribly inefficient to view in many PDF viewers.
This is the only possible problem I can think of with going to `pcolormesh`.

Anyone has experience with `pcolormesh` and `imshow` or an opinion here?

Anyone has time to make a pull request for this before the Gammapy tutorials at MPIK on Tuesday afternoon?
(this is the most visible issue in the Gammapy tutorial notebooks, and was heavily discussed in Paris, in the context of when to issue warnings or not and how to handle known issues on the project page)

**Comment by kosack** [comment]
The main reason to use it is that `pcolormesh` doesn't require square pixels or even spacing of pixels, but otherwise it is slower and produces larger output. It renders each pixel as a box to produce an image, but then you are always guaranteed the axes are correct, since there can be no mismatch unlike within imshow.

**Comment by kosack** [comment]
I'd say for some images (like skymaps), where the pixels are square and the axes are linear,  `imshow` is the better one to use, however for plotting 2D histograms/IRFs/etc you should use `pcolormesh`. It even supports logarithmic axes.

**Comment by joleroi** [comment]
> however for plotting 2D histograms/IRFs/etc you should use pcolormesh. It even supports logarithmic axes.

:+1:

**Comment by cdeil** [comment]
Ah ... yes, agreed. We should use `pcolormesh` for all the IRF plots. (pretty much all cases where we call `imshow` now.

**Comment by cdeil** [comment]
So with #933 merged the EDISP plot is fixed. Thanks @adonath !

Executing the example snippet given above I see this:

<img width="752" alt="screen shot 2017-03-05 at 18 32 41" src="https://cloud.githubusercontent.com/assets/852409/23589707/45aa457c-01d2-11e7-95f6-3f199b5401b7.png">


@adonath - I think you missed one IRF plot where we should go imshow -> edisp:
```
$ ack imshow
<snip>
gammapy/irf/energy_dispersion.py
907:        ax.imshow(z.transpose(), extent=extent, origin='bottom', **kwargs)
<snip>
```
https://github.com/gammapy/gammapy/blob/master/gammapy/irf/energy_dispersion.py#L907
Can you please do that last one also?

**Comment by cdeil** [comment]
@adonath - I've re-run the IACT data notebook. See https://gist.github.com/cdeil/6227bedaad8487888f3867730b4b3c55

Indeed the EDISP bias plot still has the issue because `imshow` is still used there.

For AEFF and PSF, the axes are now switched.
- Before: x=offset, y=energy
- Now: x=energy, y=offset

I think I slightly prefer the old version, but probably that's just because I got used to it.
@adonath @joleroi - Any preference concerning which parameter to put on which axis in those plots?

**Comment by adonath** [comment]
@cdeil I added the replacement of  `imshow()` in #936. 

While in principle for an image plot it doesn't matter, the x-axis is often considered as the independent axis. I slightly prefer energy on the x-axis, because energy dependence seems to be the more common case for our IRF classes. Typically we evaluate at one given offset and keep the energy dependence.

**Comment by cdeil** [comment]
I have no strong preference, so let's merge #936 for now and move on.
We can always re-discuss as we get feedback from others.
Closing this issue now.

@TarekHC - Do you still see the sky image plotting issue you mentioned above?
If yes, could you please open a new issue for it?
(and paste the image you're getting that shows the bug via drag & drop of the PNG into the Github issue edit field).

**Comment by adonath** [comment]
@TarekHC The sky image plotting should be resolved, when #941 is merged (fixed by [this](https://github.com/gammapy/gammapy/pull/941/files#diff-bfb05eb798826cb17a9c1246b3ef5567R901) line).

**Comment by TarekHC** [comment]
@adonath I just installed your branch, and the problem seems to be not solved...

Noob question: "python setup install" should be enough to use that version of gammapy, right?

@cdeil I'll do a new issue now.
